[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python voice_assistant_server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
watchPaths = ["voice_assistant_server.py", "voice_assistant_bot.py"]

[environments.production.variables]
PORT = "8000"
HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"