[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python voice_assistant_server.py"
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "8000"
HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"